ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.mtaanimation.growthos.backend.ApplicationKt.module ]
    }
}
jwt {
    domain = "https://mtaanalytics.onrender.com"
    audience = "mtaanalytics-users"
    realm = "mtaanimation-growthos"
    secret = "secret-key-change-in-production"
    secret = ${?JWT_SECRET}
}
database {
    url = "jdbc:postgresql://localhost:5432/growthos"
    url = ${?DATABASE_URL}
    user = "mtauser"
    user = ${?DATABASE_USER}
    password = "mtapassword"
    password = ${?DATABASE_PASSWORD}
}
