ktor {
    deployment {
        port = 8080
        port = \${?PORT}
    }
    application {
        modules = [ com.mtaanimation.growthos.backend.ApplicationKt.module ]
    }
}
jwt {
    domain = "https://jwt-provider-domain/"
    audience = "jwt-audience"
    realm = "mtaanimation-growthos"
    secret = "secret-key-change-in-production"
}
database {
    url = "jdbc:postgresql://localhost:5432/growthos"
    url = \${?DATABASE_URL}
    user = "mtauser"
    user = \${?DATABASE_USER}
    password = "mtapassword"
    password = \${?DATABASE_PASSWORD}
}
